#!/usr/bin/env bash
# WisprFlow - uninstall (removes user-local install)
# Generated by install.sh; safe to run manually.
set -euo pipefail
XDG_BIN_HOME="${XDG_BIN_HOME:-$HOME/.local/bin}"
XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
XDG_DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"
echo "==> Stopping services..."
systemctl --user disable --now wispr-flow.service 2>/dev/null || true
pkill -x wispr-flow 2>/dev/null || true
pkill -x wispr-flow-ui 2>/dev/null || true
echo "==> Removing binaries..."
rm -f "$XDG_BIN_HOME/wispr-flow" "$XDG_BIN_HOME/wispr-flow-ui"
rm -rf "$HOME/.local/lib/wispr-flow"
echo "==> Removing autostart & service..."
rm -f "$XDG_CONFIG_HOME/autostart/wispr-flow.desktop"
rm -f "$XDG_CONFIG_HOME/systemd/user/wispr-flow.service"
systemctl --user daemon-reload 2>/dev/null || true
echo "==> Data/config kept (remove manually if desired):"
echo "    $XDG_DATA_HOME/wispr-flow/"
echo "    $XDG_CONFIG_HOME/wispr-flow/"
echo "    $HOME/.local/share/wispr-flow/  (legacy)"
echo "    models/  (in repo checkout)"
echo "To fully remove config/data: rm -rf \"\$XDG_CONFIG_HOME/wispr-flow\" \"\$XDG_DATA_HOME/wispr-flow\""
echo "Done."
